name: alanoapp
description: "App para membros do canal AlanoCryptoFX"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_app_check: ^0.3.1+4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.2.10
  google_sign_in: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  timeago: ^3.7.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  universal_html: ^2.2.4
  cloud_functions: ^5.6.2
  photo_view: ^0.15.0
  rxdart: ^0.28.0
  mask_text_input_formatter: ^2.9.0
  youtube_player_flutter: ^8.1.2
  fl_chart: ^0.65.0
  crypto_font_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  gh_pages: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/